services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  clamav:
    image: clamav/clamav:latest
    ports:
      - "3310:3310"
    volumes:
      - ./test-data:/tmp/virusscan
      - clamav-db:/var/lib/clamav

  producer:
    build:
      context: .
      args:
        FLAVOR: producer
    command: virus-scanner-producer
    ports:
      - "50051:50051" # gRPC
      - "8080:8080" # Metrics
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SCAN_TMP_DIR=/tmp/virusscan
      - SCAN_FILE_THRESHOLD_MB=10
      - TENANT_ID=local-test-tenant
    volumes:
      - ./test-data:/tmp/virusscan
    depends_on:
      - redis

  handler:
    build:
      context: .
      args:
        FLAVOR: consumer
    environment:
      - REDIS_HOST=redis
      - CLAMD_URL=tcp://clamav:3310
      - CONSOLE_API_URL=http://localhost:3000
      - SCAN_MOUNT=/tmp/virusscan
    volumes:
      - ./test-data:/tmp/virusscan
    depends_on:
      - redis
      - clamav

volumes:
  clamav-db:
