apiVersion: v1
kind: Service
metadata:
  name: {{ include "shared-clamav.fullname" . }}-producer
  labels:
    {{- include "shared-clamav.labels" . | nindent 4 }}
    app.kubernetes.io/component: producer
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.service.producer.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.producer.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "shared-clamav.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: producer
