{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
kind: RoleBinding
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "common.names.fullname" . }}
  apiGroup: "" # Default API group for ServiceAccount
roleRef:
  kind: Role
  name: {{ include "common.names.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}