# JupyterHub Egress Gateway Envoy Configuration Sample
# This sample provides a working Envoy configuration for Virus Scanning via External Processing (ext_proc).
# It has been corrected to remove the unsupported 'processing_timeout' field.

static_resources:
  listeners:
    - name: egress_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8443
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: egress_http
                route_config:
                  name: egress_route
                  virtual_hosts:
                    - name: any_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: original_destination_cluster
                http_filters:
                  - name: envoy.filters.http.ext_proc
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
                      grpc_service:
                        envoy_grpc:
                          cluster_name: virus_scanner_producer
                      failure_mode_allow: true # Set to true to avoid blocking all traffic if scanner is down
                      processing_mode:
                        request_body_mode: BUFFERED
                        response_body_mode: BUFFERED
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: virus_scanner_producer
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      load_assignment:
        cluster_name: virus_scanner_producer
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: virus-scanner-producer.aether-system.svc.cluster.local
                      port_value: 50051
    - name: original_destination_cluster
      type: ORIGINAL_DST
      lb_policy: CLUSTER_PROVIDED
      connect_timeout: 5s
