apiVersion: v2
name: shared-clamav
description: A Helm chart for Shared ClamAV with Redis Queue and KEDA scaling.
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 19.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    alias: redis
